source :rubygems

group "development" do
  # chef and vagrant require different versions of json, so we have to force the version manually
  gem "json",                   "1.5.2"

  gem "elzar"
  gem "vagrant",                "1.0.5"
  gem "chef",                   "10.14.4"
  gem "knife-solo",             "0.0.14"
  gem "knife-github-cookbooks", "~> 0.1.7"
end
