source :rubygems

group "development" do
  # chef and vagrant require different versions of json, so we have to force the version manually
  gem "json",                   "1.5.2"

  gem "elzar"
  gem "vagrant",                "0.8.7"
  gem "chef",                   "0.10.8"
  gem "knife-solo",             "0.0.4"
  gem "knife-github-cookbooks", :git => "git://github.com/sumbach/knife-github-cookbooks.git"
end
