#!/bin/bash

source "$HOME/.rvm/scripts/rvm"
export CI_RUBY_VERSION="ruby-1.9.3-p194"
export CI_GEMSET=elzar_nightly

# Tests and app are all running in CI_GEMSET
export NO_RVM=true

rvm use "$CI_RUBY_VERSION@$CI_GEMSET"
gem install bundler
bundle install

bundle exec rspec --tag ci
